/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;

/**
 *
 * @author nguye
 */
public class ClientGUI extends javax.swing.JFrame {
    Patron patron;
    /**
     * Creates new form ClientGUI
     */
    class ClientImpl extends UnicastRemoteObject implements ClientInterface {

        public ClientImpl() throws RemoteException {
        }

        @Override
        public void notify(NOTIFY notify) throws RemoteException {

            if (notify == NOTIFY.CLIENT_UPDATE_NOTIFICATION) showNotification();

        }
    }
    ClientController controller;
    private void showNotification() {
        try {
            Response response = controller.getNotificationByPatronId(patron.getId());
            if (response.getStatus() == 100) {
                JOptionPane.showMessageDialog(this, response.getData());
            }
            tbl_Notification.setModel((DefaultTableModel) response.getData());
//            tbl_Notification.getTableHeader().setDefaultRenderer(new CustomHeaderRenderer());
            tbl_Notification.setRowHeight(50);
            tbl_Notification.setDefaultEditor(Object.class, null);
            sp_Notification.setViewportView(tbl_Notification);
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }

    public ClientGUI(Patron patron) {
        initComponents();
        this.patron = patron;
        setTitle("Login to VKU Library - " + patron.getEmail());

        try {
            controller = new ClientController(new ClientImpl());
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        showNotification();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        panel_main = new javax.swing.JTabbedPane();
        panel_Home = new javax.swing.JPanel();
        sp_Notification = new javax.swing.JScrollPane();
        tbl_Notification = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_Hold = new javax.swing.JPanel();
        panel_Checkout = new javax.swing.JPanel();
        panel_Profile = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_main.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        panel_main.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        sp_Notification.setViewportView(tbl_Notification);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book (2).png"))); // NOI18N

        btn_Exit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btn_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btn_Exit.setText("Log out - Exit app");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reading_1.png"))); // NOI18N
        jLabel4.setText("Welcome to VKU Library");

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        jLabel2.setText("Notification");

        javax.swing.GroupLayout panel_HomeLayout = new javax.swing.GroupLayout(panel_Home);
        panel_Home.setLayout(panel_HomeLayout);
        panel_HomeLayout.setHorizontalGroup(
                panel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_HomeLayout.createSequentialGroup()
                                .addGroup(panel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_HomeLayout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(panel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                                        .addComponent(btn_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_HomeLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel5)
                                                .addGap(31, 31, 31)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(panel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sp_Notification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
        );
        panel_HomeLayout.setVerticalGroup(
                panel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_HomeLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panel_HomeLayout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addGap(155, 155, 155)
                                                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30))
                                        .addGroup(panel_HomeLayout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sp_Notification, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21))))
        );

        panel_main.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/images/growth.png")), panel_Home); // NOI18N

        javax.swing.GroupLayout panel_HoldLayout = new javax.swing.GroupLayout(panel_Hold);
        panel_Hold.setLayout(panel_HoldLayout);
        panel_HoldLayout.setHorizontalGroup(
                panel_HoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1200, Short.MAX_VALUE)
        );
        panel_HoldLayout.setVerticalGroup(
                panel_HoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 612, Short.MAX_VALUE)
        );

        panel_main.addTab("Borrow Book", new javax.swing.ImageIcon(getClass().getResource("/images/reading_32.png")), panel_Hold); // NOI18N

        javax.swing.GroupLayout panel_CheckoutLayout = new javax.swing.GroupLayout(panel_Checkout);
        panel_Checkout.setLayout(panel_CheckoutLayout);
        panel_CheckoutLayout.setHorizontalGroup(
                panel_CheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1200, Short.MAX_VALUE)
        );
        panel_CheckoutLayout.setVerticalGroup(
                panel_CheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 612, Short.MAX_VALUE)
        );

        panel_main.addTab("Return Book", new javax.swing.ImageIcon(getClass().getResource("/images/download (1).png")), panel_Checkout); // NOI18N

        javax.swing.GroupLayout panel_ProfileLayout = new javax.swing.GroupLayout(panel_Profile);
        panel_Profile.setLayout(panel_ProfileLayout);
        panel_ProfileLayout.setHorizontalGroup(
                panel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1200, Short.MAX_VALUE)
        );
        panel_ProfileLayout.setVerticalGroup(
                panel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 612, Short.MAX_VALUE)
        );

        panel_main.addTab("Profile", new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png")), panel_Profile); // NOI18N

        getContentPane().add(panel_main, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/client_banner.png"))); // NOI18N
        jPanel5.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.NORTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {

    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panel_Checkout;
    private javax.swing.JPanel panel_Hold;
    private javax.swing.JPanel panel_Home;
    private javax.swing.JPanel panel_Profile;
    private javax.swing.JTabbedPane panel_main;
    private javax.swing.JScrollPane sp_Notification;
    private javax.swing.JTable tbl_Notification;
    // End of variables declaration
}
